[package]
name = "dynrust"
version = "0.1.0"
authors = ["kaaboaye <kaaboaye@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.5"
lazy_static = "1"
ctrlc = "3"
